### PR TITLE
(#2054725) ci: Add Differential ShellCheck action

### PR DESCRIPTION
**Pull request by jamacku**
Related: #2054725

### CODE REVIEW

**Comment by pvalena** [comment]
[test]

**Comment by pvalena** [comment]
Can't find the logs. How to restart tests?

_Maybe I don't have the permissions?_

**Comment by jamacku** [comment]
@pvalena now you should be able to see [logs](https://github.com/redhat-plumbers/dracut-rhel8/runs/6467271262?check_suite_focus=true) and also re-run test. I don't know why it wasn't possible before.

**Comment by pvalena** [comment]
> @pvalena now you should be able to see [logs](https://github.com/redhat-plumbers/dracut-rhel8/runs/6467271262?check_suite_focus=true) and also re-run test. I don't know why it wasn't possible before.

Yes, now I can do both. It was probably too old / archived run.


```
No bugs added Yay!

```

I take it this is a sign that it works! Let's see when we run some real RP with it.

**Comment by pvalena** [comment]
Thanks!

**Pull request merged**
