### PR TITLE
(#2007586) Backport: fix(fips): handle s390x OSTree systems

### PR DESCRIPTION
**Pull request by pvalena**
https://github.com/dracutdevs/dracut/pull/1539
https://bugzilla.redhat.com/show_bug.cgi?id=2007586

### CODE REVIEW

**Comment by pvalena** [comment]
TODO: I will polish this
i.e. replace find, cut, sed if possible

**Comment by pvalena** [comment]
I've rewritten it a bit:
https://gist.github.com/a3cc7555b97feee29afe4a7bfbd36d29

I'm not sure `ls -r` would be suitable replacement here. So I've kept the `sort`. Tested:
```
# echo $BOOT_IMAGE
1
#                 i=0
                for bls in $(ls -d /boot/loader/entries/*.conf | sort -rV); do
                  ((i++))

                  if [ $i -eq ${BOOT_IMAGE:-0} ] && [ -r "$bls" ]; then
                      BOOT_IMAGE="$(grep -e '^linux' "$bls" | grep -o ' .*$')"
                      BOOT_IMAGE=${BOOT_IMAGE:1}
                      break
                  fi
                done

# echo $BOOT_IMAGE
/vmlinuz-5.16.0-0.rc3.20211203git5f58da2befa5.26.fc36.x86_64

```

**Review by lnykryn — APPROVED** [review]

**Comment by pvalena** [comment]
@lnykryn ready to merge?

**Comment by lnykryn** [comment]
yup, I was waiting for release+

**Comment by nikita-dubrovskii** [comment]
Hi all.
Don't you know when new rpms land to http://rhsm-pulp.corp.redhat.com/content/dist/rhel8/8.5/s390x/baseos/os/ ?

**Comment by pvalena** [comment]
> Hi all. Don't you know when new rpms land to http://rhsm-pulp.corp.redhat.com/content/dist/rhel8/8.5/s390x/baseos/os/ ?

@nikita-dubrovskii
For 8.5 please follow https://bugzilla.redhat.com/show_bug.cgi?id=2054683

**Comment by nikita-dubrovskii** [comment]
Thx. today i've tested new RPM and unfortunately it contains another bug:
```
i=0
for bls in $(ls -d /boot/loader/entries/*.conf | sort -rV); do
    ((i++))
    if [ $i -eq ${BOOT_IMAGE:-0} ] && [ -r "$bls" ]; then
```

`BOOT_IMAGE` by default is `0`. so this `if - then` is always `false`.  original PR from @jlebon was a bit easier: 

```
bls=$(find /boot/loader/entries -name '*.conf' | sort -rV | sed -n "$((BOOT_IMAGE + 1))p")
```

so we had a proper `*-1-*.conf` BLS config

**Comment by pvalena** [comment]
> Thx. today i've tested new RPM and unfortunately it contains another bug:
> 
> ```
> i=0
> for bls in $(ls -d /boot/loader/entries/*.conf | sort -rV); do
>     ((i++))
>     if [ $i -eq ${BOOT_IMAGE:-0} ] && [ -r "$bls" ]; then
> ```
> 
> `BOOT_IMAGE` by default is `0`. so this `if - then` is always `false`. original PR from @jlebon was a bit easier:
> 
> ```
> bls=$(find /boot/loader/entries -name '*.conf' | sort -rV | sed -n "$((BOOT_IMAGE + 1))p")
> ```
> 
> so we had a proper `*-1-*.conf` BLS config

[response in the BZ]

FTR, addressed in https://github.com/redhat-plumbers/dracut-rhel8/pull/16

**Pull request merged**
