### PR TITLE
fix(udev-rules): keep network device naming scheme on upgrade

### PR DESCRIPTION
**Pull request by pvalena**
(Cherry-picked commit: 2fc6cd37e61e53333d57164eee79e90c6adcade6)

Resolves: RHEL-9480

### CODE REVIEW

**Comment by pvalena** [comment]
@lnykryn PTAL.

**Comment by lnykryn** [comment]
Chmm, I am not thrilled about this; I can imagine where a user depends on this broken behaviour and mounts some network fs via the kernel name of the device. I think this fix makes sense upstream, but I am really worried about putting this in the last minor version of rhel8.

**Comment by pvalena** [comment]
It's just "hostonly", so I hoped it shouldn't do anything apart from fixing the behaviour, right? Maybe it deserves a RN. I'm not sure why would someone depend on missing this behaviour, and expect it to persist ([RHELDOCS-16507#comment](https://issues.redhat.com/browse/RHELDOCS-16507?focusedId=23122824&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23122824)) The file does not exist by default, right?

Based on the ticket [1] I thought this would be the correct fix, especially if it's in the documentation.

[1] https://issues.redhat.com/browse/RHEL-9480

**Comment by lnykryn** [comment]
Can you please skip this one for now, I need some time to think about this. And hostonly is the default and in the setup I have mentioned you definitely have hostonly initrd

**Comment by pvalena** [comment]
Let's drop this, as there're is no demand to resolve this issue.

**Pull request closed without merging**
